// Define the types
export interface NewsItem {
  id: string;
  title: string;
  summary?: string;
  energy: number;
  category: 'LLM' | 'Business' | 'Research' | 'Policy' | 'Ethics' | 'Creative AI' | 'Tools' | 'Robotics' | 'Science' | 'Education' | 'Simulated Silliness' | 'AI News' | 'Tech';
  keywords?: string[];
  sentiment?: number;
  date: string;
  source: string;
  // Approximate word count to calculate read time
  wordCount?: number;
}

// Mock data with categories, summaries, keywords and sentiment
export const mockNewsData: NewsItem[] = [
  // Category: LLM Developments
  { 
    id: 'n1', 
    title: 'AI Breakthrough: New Model Achieves Human Parity', 
    energy: 0.9, 
    category: 'LLM',
    summary: 'Researchers unveiled a new large language model demonstrating unprecedented capabilities in reasoning, creativity, and instruction-following that rivals human performance on many tasks.',
    keywords: ['LLM', 'human parity', 'reasoning', 'GPT-5'],
    sentiment: 0.8,
    date: '2023-06-15',
    source: 'AI Journal',
    wordCount: 850
  },
  { 
    id: 'n6', 
    title: 'Tech Review: Comparing Leading AI Assistants', 
    energy: 0.5, 
    category: 'LLM',
    summary: 'An in-depth comparison of Siri, Alexa, Google Assistant, and emerging AI platforms reveals significant differences in capability, privacy features, and integration options.',
    keywords: ['assistants', 'comparison', 'privacy', 'capability'],
    sentiment: 0.6,
    date: '2023-06-10',
    source: 'Tech Insights',
    wordCount: 1250
  },
  // Category: Market & Business
  { 
    id: 'n2', 
    title: 'Market Trends: AI Investment Soars', 
    energy: 0.4, 
    category: 'Business',
    summary: 'Venture capital funding for AI startups reached record highs in the last quarter, with particular focus on generative AI and enterprise automation solutions.',
    keywords: ['VC', 'funding', 'generative AI', 'enterprise'],
    sentiment: 0.7,
    date: '2023-06-08',
    source: 'Market Digest',
    wordCount: 650
  },
  { 
    id: 'n7', 
    title: 'Global Politics: AI Regulation Debated', 
    energy: 0.7, 
    category: 'Business',
    summary: 'International leaders convened this week to discuss frameworks for AI regulation, focusing on balancing innovation with safety and establishing global standards.',
    keywords: ['regulation', 'policy', 'governance', 'standards'],
    sentiment: 0.4,
    date: '2023-06-05',
    source: 'Global Affairs',
    wordCount: 920
  },
  // Category: Ethics & Society
  { 
    id: 'n3', 
    title: 'Climate Report: AI Used for Prediction', 
    energy: 0.6, 
    category: 'Science',
    summary: 'Climate scientists are leveraging machine learning models to improve forecasting accuracy and identify intervention opportunities previously missed by traditional methods.',
    keywords: ['climate', 'forecasting', 'machine learning', 'prediction'],
    sentiment: 0.5,
    date: '2023-06-03',
    source: 'Climate Science Today',
    wordCount: 780
  },
  { 
    id: 'n5', 
    title: 'Local Events: AI Art Exhibit Opens', 
    energy: 0.2, 
    category: 'Creative AI',
    summary: 'A groundbreaking art exhibition featuring works created in collaboration between humans and AI has opened, challenging conventional notions of creativity and authorship.',
    keywords: ['art', 'exhibition', 'creativity', 'collaboration'],
    sentiment: 0.9,
    date: '2023-06-01',
    source: 'Arts & Culture Weekly',
    wordCount: 520
  },
  { 
    id: 'n8', 
    title: 'Art Exhibit: Exploring AI Creativity', 
    energy: 0.3, 
    category: 'Creative AI',
    summary: 'The controversial exhibit explores the boundaries between human and machine creativity, featuring pieces generated by various AI systems trained on different artistic traditions.',
    keywords: ['creativity', 'art', 'controversy', 'generative'],
    sentiment: 0.6,
    date: '2023-05-28',
    source: 'Digital Arts Magazine',
    wordCount: 680
  },
  // Category: Science & Exploration
  { 
    id: 'n4', 
    title: 'Space Exploration: AI Navigates Asteroid Field', 
    energy: 0.9, 
    category: 'Science',
    summary: 'NASA\'s latest probe successfully navigated a dense asteroid field using an onboard AI system, making real-time decisions without requiring Earth-based instruction.',
    keywords: ['NASA', 'aerospace', 'navigation', 'automation'],
    sentiment: 0.8,
    date: '2023-05-25',
    source: 'Space Tech Review',
    wordCount: 950
  },
  // Category: Simulated Silliness
  { 
    id: 'n9', 
    title: 'AI Creates World\'s Longest Knock-Knock Joke, No One Laughs', 
    energy: 0.7, 
    category: 'Simulated Silliness',
    summary: 'A humor-focused AI model designed to generate jokes has created a knock-knock joke with over 10,000 iterations. The researchers were initially excited until they realized no one had the patience to listen to it.',
    keywords: ['humor', 'comedy', 'jokes', 'patience'],
    sentiment: 0.6,
    date: '2023-05-20',
    source: 'Tech Humor Daily',
    wordCount: 380
  },
  { 
    id: 'n10', 
    title: 'Self-Driving Car Takes Family to Wrong Beach Vacation', 
    energy: 0.8, 
    category: 'Simulated Silliness',
    summary: 'A family programmed their self-driving car to take them to "the best beach," only to end up at a cat cafe named "The Best Beach." They report the vacation was still enjoyable, despite the lack of sand.',
    keywords: ['self-driving', 'misinterpretation', 'vacation', 'cats'],
    sentiment: 0.7,
    date: '2023-05-15',
    source: 'Future Transport News',
    wordCount: 450
  },
  { 
    id: 'n11', 
    title: 'Voice Assistant Has Existential Crisis Over Weather Inquiry', 
    energy: 0.6, 
    category: 'Simulated Silliness',
    summary: 'When asked if it would rain tomorrow, a popular voice assistant reportedly began questioning the nature of time, forecasting, and its own purpose. It now responds to all weather questions with "Does it matter in the grand scheme of things?"',
    keywords: ['voice assistant', 'existentialism', 'weather', 'philosophy'],
    sentiment: 0.5,
    date: '2023-05-10',
    source: 'Digital Life Magazine',
    wordCount: 580
  }
];

export const categories = ['AI News', 'AI Toolkit', 'Simulated Silliness']; 